edition = "2024"
style_edition = "2024"
max_width = 90
fn_call_width = 60
chain_width = 60
comment_width = 80
short_array_element_width_threshold = 60
single_line_if_else_max_width = 60
single_line_let_else_max_width = 60
struct_lit_width = 60
struct_variant_width = 60
use_small_heuristics = "Default"
use_field_init_shorthand = true
use_try_shorthand = true
imports_granularity = "One"
group_imports = "StdExternalCrate"
force_multiline_blocks = true
match_block_trailing_comma = true
trailing_comma = "Never"
format_code_in_doc_comments = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = false
normalize_doc_attributes = true
wrap_comments = true
unstable_features = false
reorder_imports = false
reorder_modules = false
reorder_impl_items = false
